#!/usr/bin/env python3
"""Generate smoke-test configs from a full production config (rule R1 in
experiment_ideas/training_run_plan.md).

Smoke configs under configuration_files/smoke/ must never be hand-edited --
regenerate them with this script so they cannot drift from the config they
were derived from. Only `episodes`, `global_iters` (non_local_opt section),
and the seed count are changed; every other key is copied through verbatim.

Tiers (training_run_plan.md sec 2):
  s0 -- mechanical:      episodes=5,   global_iters unchanged, 1 seed
  s1 -- learning smoke:  episodes=300, global_iters=200,       2 seeds

Usage:
  python scripts/make_smoke_cfg.py configuration_files/TensorRL_fixed/BEH26q_TNbond2.cfg --tier s0
  python scripts/make_smoke_cfg.py configuration_files/TensorRL_fixed/H2O8q_TNbond2.cfg --tier s1
"""
import argparse
import configparser
import datetime
import pathlib

TIER_DEFAULTS = {
    "s0": {"episodes": 5, "global_iters": None, "seeds": 1},
    "s1": {"episodes": 300, "global_iters": 200, "seeds": 2},
}


def make_smoke_cfg(source_path, tier, episodes=None, global_iters=None, seeds=None,
                    output_dir=pathlib.Path("configuration_files/smoke")):
    defaults = TIER_DEFAULTS[tier]
    episodes = defaults["episodes"] if episodes is None else episodes
    global_iters = defaults["global_iters"] if global_iters is None else global_iters
    seeds = defaults["seeds"] if seeds is None else seeds

    source_path = pathlib.Path(source_path)
    parser = configparser.ConfigParser()
    read_ok = parser.read(source_path)
    if not read_ok:
        raise FileNotFoundError(f"could not read source config: {source_path}")

    parser["general"]["episodes"] = str(episodes)
    if global_iters is not None:
        parser["non_local_opt"]["global_iters"] = str(global_iters)

    output_dir = pathlib.Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{source_path.stem}_{tier}_smoke.cfg"

    header = (
        f"; AUTO-GENERATED by scripts/make_smoke_cfg.py -- do not hand-edit (rule R1)\n"
        f"; source: {source_path}\n"
        f"; tier: {tier}  episodes={episodes}  global_iters={global_iters}  seeds={seeds}\n"
        f"; generated: {datetime.datetime.now().isoformat(timespec='seconds')}\n"
    )
    with open(output_path, "w") as f:
        f.write(header)
        parser.write(f)

    return output_path, seeds


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source_config", help="Path to the full production .cfg")
    ap.add_argument("--tier", choices=sorted(TIER_DEFAULTS), default="s0")
    ap.add_argument("--episodes", type=int, default=None, help="Override tier default")
    ap.add_argument("--global-iters", type=int, default=None, help="Override tier default")
    ap.add_argument("--seeds", type=int, default=None, help="Override tier default (informational; caller loops seeds)")
    ap.add_argument("--output-dir", type=pathlib.Path, default=pathlib.Path("configuration_files/smoke"))
    args = ap.parse_args()

    output_path, seeds = make_smoke_cfg(
        args.source_config, args.tier, args.episodes, args.global_iters, args.seeds, args.output_dir
    )
    print(f"Wrote {output_path} (tier={args.tier}, seeds={seeds})")


if __name__ == "__main__":
    main()
